18:41:52 INFO GitHub token rate limit: Rate(reset=2025-05-04 19:21:55+00:00, remaining=4713, limit=5000)
18:42:18 INFO Waiting for model:
  test-mbok9p2j/0 [executing] active: 
18:42:48 INFO Waiting for model:
  test-mbok9p2j/0 [idle] active: 
18:42:55 INFO Wait for condition not met, sleeping 10
18:43:06 INFO Wait for condition not met, sleeping 60
18:44:07 INFO Wait for condition not met, sleeping 60
18:45:07 INFO Wait for condition not met, sleeping 60
18:46:08 INFO Wait for condition not met, sleeping 60
18:47:08 INFO Wait for condition not met, sleeping 60
18:48:09 INFO Wait for condition not met, sleeping 60
18:49:09 INFO Wait for condition not met, sleeping 60
18:50:10 INFO Wait for condition not met, sleeping 60
18:51:10 INFO Wait for condition not met, sleeping 60
18:52:11 INFO Wait for condition not met, sleeping 60
18:53:11 INFO Wait for condition not met, sleeping 60
18:54:12 INFO Wait for condition not met, sleeping 60
18:55:12 INFO Wait for condition not met, sleeping 60
18:56:13 INFO Wait for condition not met, sleeping 60
18:57:13 INFO Wait for condition not met, sleeping 60
18:58:14 INFO Wait for condition not met, sleeping 60
18:59:14 INFO Wait for condition not met, sleeping 60
19:00:15 INFO Wait for condition not met, sleeping 60
19:01:15 INFO Wait for condition not met, sleeping 60
19:02:16 INFO Wait for condition not met, sleeping 60
19:03:16 INFO Wait for condition not met, sleeping 60
19:04:17 INFO Wait for condition not met, sleeping 60
19:05:17 INFO Wait for condition not met, sleeping 60
19:06:18 INFO Wait for condition not met, sleeping 60
19:07:18 INFO Wait for condition not met, sleeping 60
19:08:19 INFO Wait for condition not met, sleeping 60
19:09:19 INFO Wait for condition not met, sleeping 60
19:10:20 INFO Wait for condition not met, sleeping 60
19:11:20 INFO Wait for condition not met, sleeping 60
19:12:21 INFO Wait for condition not met, sleeping 60
19:13:23 INFO Model status:

Model                            Controller           Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-success-jrqc  github-pr-b51b1-lxd  localhost/localhost  3.6.5    unsupported  19:13:23Z

App                                   Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-mbok9p2j           active      1  github-runner-image-builder  latest/edge   68  no       
test-mbok9p2j                                  active      1  github-runner                               0  no       

Unit                                     Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder-mbok9p2j/0*  active    idle   0        10.69.25.58            
test-mbok9p2j/0*                         active    idle   1        10.69.25.226           

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.69.25.58   juju-eeff60-0  ubuntu@22.04      Running
1        started  10.69.25.226  juju-eeff60-1  ubuntu@22.04      Running

19:13:24 INFO Juju error logs:

machine-0: 18:25:15 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:25:15 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-mbok9p2j-0: 18:25:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 18:25:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:25:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-mbok9p2j-0: 18:25:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-github-runner-image-builder-mbok9p2j-0: 18:25:58 ERROR unit.github-runner-image-builder-mbok9p2j/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-mbok9p2j-0: 18:25:59 ERROR unit.test-mbok9p2j/0.juju-log Command python3 -m pip uninstall github_runner_manager failed with code 2: b'ERROR: Exception:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper\n    status = _inner_run()\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run\n    return self.run(options, args)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 106, in run\n    uninstall_pathset = req.uninstall(\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 723, in uninstall\n    uninstalled_pathset.remove(auto_confirm, verbose)\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 364, in remove\n    if auto_confirm or self._allowed_to_proceed(verbose):\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 404, in _allowed_to_proceed\n    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"\n  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 229, in ask\n    response = input(message)\nEOFError: EOF when reading a line\n'
unit-test-mbok9p2j-0: 18:41:05 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:11 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:15 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:15 ERROR unit.test-mbok9p2j/0.juju-log Failed to get SSH connection while removing test-mbok9p2j-0-n-4d3b0f8c7f1e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key
unit-test-mbok9p2j-0: 18:41:18 ERROR unit.test-mbok9p2j/0.juju-log Invalid pulled metrics. No runner_installed information for test-mbok9p2j-0-n-4d3b0f8c7f1e.
unit-test-mbok9p2j-0: 18:41:18 ERROR unit.test-mbok9p2j/0.juju-log No metrics returned after deleting test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:23 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:26 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:41:29 ERROR unit.test-mbok9p2j/0.juju-log Failed to get SSH connection while removing test-mbok9p2j-0-n-4d3b0f8c7f1e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key
unit-test-mbok9p2j-0: 18:41:31 ERROR unit.test-mbok9p2j/0.juju-log Invalid pulled metrics. No runner_installed information for test-mbok9p2j-0-n-4d3b0f8c7f1e.
unit-test-mbok9p2j-0: 18:41:34 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:02 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:05 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:06 ERROR unit.test-mbok9p2j/0.juju-log Failed to get SSH connection while removing test-mbok9p2j-0-n-4d3b0f8c7f1e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key
unit-test-mbok9p2j-0: 18:42:08 ERROR unit.test-mbok9p2j/0.juju-log Invalid pulled metrics. No runner_installed information for test-mbok9p2j-0-n-4d3b0f8c7f1e.
unit-test-mbok9p2j-0: 18:42:08 ERROR unit.test-mbok9p2j/0.juju-log No metrics returned after deleting test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:14 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:17 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:21 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:25 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:25 ERROR unit.test-mbok9p2j/0.juju-log Failed to get SSH connection while removing test-mbok9p2j-0-n-4d3b0f8c7f1e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 311, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key
unit-test-mbok9p2j-0: 18:42:27 ERROR unit.test-mbok9p2j/0.juju-log Invalid pulled metrics. No runner_installed information for test-mbok9p2j-0-n-4d3b0f8c7f1e.
unit-test-mbok9p2j-0: 18:42:27 ERROR unit.test-mbok9p2j/0.juju-log No metrics returned after deleting test-mbok9p2j-0-n-4d3b0f8c7f1e
unit-test-mbok9p2j-0: 18:42:34 ERROR unit.test-mbok9p2j/0.juju-log Unable to get SSH connection for instance test-mbok9p2j-0-n-4d3b0f8c7f1e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 132, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 142, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 341, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-mbok9p2j-0-n-4d3b0f8c7f1e, key path: /home/runner-manager/.ssh/test-mbok9p2j-0-n-4d3b0f8c7f1e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-mbok9p2j-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 135, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.instance_id}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-mbok9p2j-0-n-4d3b0f8c7f1e

19:13:24 INFO Forgetting model main...