INFO     pytest_operator.plugin:plugin.py:745 Adding model lxd:test-charm-scheduled-events-brrf on cloud localhost
WARNING  juju.client.connection:connection.py:893 unexpected facade AgentLifeFlag received from the controller
WARNING  juju.client.connection:connection.py:909 unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
WARNING  juju.client.connection:connection.py:893 unexpected facade SecretsDrain received from the controller
INFO     juju.model:model.py:1988 Deploying ch:amd64/github-runner-image-builder-2
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder (not enough units yet - 0/1)
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: agent initialising
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:1988 Deploying local:jammy/github-runner-0
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: installing charm software
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [idle] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Update image for runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [idle] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [idle] active:
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [idle] active: 
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-rgj5qfzb/0 [executing] maintenance: Reconciling runners
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                             Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-scheduled-events-brrf  lxd         localhost/localhost  3.1.10   unsupported  06:48:39Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-rgj5qfzb                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.228.155.25          
test-rgj5qfzb/0*                active    idle   1        10.228.155.89          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.228.155.25  juju-b03213-0  ubuntu@22.04      Running
1        started  10.228.155.89  juju-b03213-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 06:24:23 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 06:24:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:24:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 06:24:23 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:29:27 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 06:29:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:29:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-rgj5qfzb-0: 06:29:27 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-rgj5qfzb-0: 06:29:41 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:43 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:46 CRITICAL unit.test-rgj5qfzb/0.juju-log image:0: test mode is enabled
unit-test-rgj5qfzb-0: 06:29:47 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:48 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:50 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:51 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:29:52 CRITICAL unit.test-rgj5qfzb/0.juju-log image:0: test mode is enabled
unit-test-rgj5qfzb-0: 06:29:53 CRITICAL unit.test-rgj5qfzb/0.juju-log image:0: test mode is enabled
unit-test-rgj5qfzb-0: 06:30:45 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:30:46 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:35:38 CRITICAL unit.test-rgj5qfzb/0.juju-log image:0: test mode is enabled
unit-test-rgj5qfzb-0: 06:36:12 ERROR unit.test-rgj5qfzb/0.juju-log image:0: pre-job-metrics.json not found for runner test-rgj5qfzb-0-6fb99f92634f
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-rgj5qfzb-0-6fb99f92634f/pre-job-metrics.json'
unit-test-rgj5qfzb-0: 06:36:12 ERROR unit.test-rgj5qfzb/0.juju-log image:0: Pre-job metrics for runner test-rgj5qfzb-0-6fb99f92634f not found, stop extracting post-jobs metrics.
unit-test-rgj5qfzb-0: 06:36:19 ERROR unit.test-rgj5qfzb/0.juju-log image:0: Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:36:19 ERROR unit.test-rgj5qfzb/0.juju-log image:0: Failed to get SSH connection while removing test-rgj5qfzb-0-6fb99f92634f
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 441, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key
unit-test-rgj5qfzb-0: 06:36:32 ERROR unit.test-rgj5qfzb/0.juju-log image:0: Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:36:38 ERROR unit.test-rgj5qfzb/0.juju-log image:0: Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:36:54 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:37:02 ERROR unit.test-rgj5qfzb/0.juju-log Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:37:02 ERROR unit.test-rgj5qfzb/0.juju-log Failed to get SSH connection while removing test-rgj5qfzb-0-6fb99f92634f
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 441, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key
unit-test-rgj5qfzb-0: 06:37:16 ERROR unit.test-rgj5qfzb/0.juju-log Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:37:23 ERROR unit.test-rgj5qfzb/0.juju-log Unable to get SSH connection for instance test-rgj5qfzb-0-6fb99f92634f, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-rgj5qfzb-0-6fb99f92634f, key path: /home/runner-manager/.ssh/test-rgj5qfzb-0-6fb99f92634f.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-rgj5qfzb-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-rgj5qfzb-0-6fb99f92634f
unit-test-rgj5qfzb-0: 06:38:26 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:43:54 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled
unit-test-rgj5qfzb-0: 06:46:03 CRITICAL unit.test-rgj5qfzb/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...