INFO     pytest_operator.plugin:plugin.py:745 Adding model lxd:test-debug-ssh-wy54 on cloud localhost
WARNING  juju.client.connection:connection.py:893 unexpected facade AgentLifeFlag received from the controller
WARNING  juju.client.connection:connection.py:909 unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
WARNING  juju.client.connection:connection.py:893 unexpected facade SecretsDrain received from the controller
INFO     juju.model:model.py:1988 Deploying ch:amd64/github-runner-image-builder-2
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder (not enough units yet - 0/1)
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] active: Waiting for first image.
INFO     juju.model:model.py:1988 Deploying local:jammy/github-runner-0
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] maintenance: installing charm software
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [idle] active: 
INFO     root:conftest.py:589 GitHub token rate limit: Rate(reset=2024-12-21 07:18:39+00:00, remaining=4883, limit=5000)
INFO     juju.model:model.py:1988 Deploying ch:amd64/jammy/tmate-ssh-server-6
WARNING  juju.model:model.py:1513 relate is deprecated and will be removed. Use integrate instead.
INFO     juju.model:model.py:2641 Waiting for model:
  tmate-ssh-server/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  tmate-ssh-server/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  tmate-ssh-server/0 [idle] active:
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [idle] active: 
  test-s4m287fw/0 [executing] maintenance: Reconciling runners
  tmate-ssh-server/0 [idle] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
  tmate-ssh-server/0 [idle] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [idle] active: 
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] active: 
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] maintenance: Update image for runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-s4m287fw/0 [executing] maintenance: Reconciling runners
INFO     tests.integration.helpers.openstack:openstack.py:104 [TEST SETUP] Run command sudo iptables -t nat -A OUTPUT -p tcp --dport 10022 -j DNAT --to-destination 127.0.0.1:10022 on test-s4m287fw-0-b89e3a691055
WARNING  tests.integration.helpers.openstack:openstack.py:106 dict_values([[{'version': 4, 'addr': '10.145.193.250', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:d1:5f:32'}]])
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                Controller  Cloud/Region         Version  SLA          Timestamp
test-debug-ssh-wy54  lxd         localhost/localhost  3.1.10   unsupported  06:35:46Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-s4m287fw                         active      1  github-runner                               0  no       
tmate-ssh-server                      active      1  tmate-ssh-server             edge           6  no       

Unit                            Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder/0*  active    idle   0        10.254.242.101             
test-s4m287fw/0*                active    idle   1        10.254.242.28              
tmate-ssh-server/0*             active    idle   2        10.254.242.246  10022/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.254.242.101  juju-5b2590-0  ubuntu@22.04      Running
1        started  10.254.242.28   juju-5b2590-1  ubuntu@22.04      Running
2        started  10.254.242.246  juju-5b2590-2  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

machine-0: 06:23:37 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 06:23:37 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 06:23:37 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-0: 06:23:37 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 06:26:37 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 06:26:37 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 06:26:37 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-s4m287fw-0: 06:26:37 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-s4m287fw-0: 06:26:52 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:26:54 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:26:57 CRITICAL unit.test-s4m287fw/0.juju-log image:0: test mode is enabled
unit-test-s4m287fw-0: 06:26:58 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:26:59 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:27:01 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:27:02 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:27:03 CRITICAL unit.test-s4m287fw/0.juju-log image:0: test mode is enabled
unit-test-s4m287fw-0: 06:27:04 CRITICAL unit.test-s4m287fw/0.juju-log image:0: test mode is enabled
unit-test-s4m287fw-0: 06:27:38 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:27:39 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
machine-2: 06:28:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 06:28:18 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 06:28:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-tmate-ssh-server-0: 06:28:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-s4m287fw-0: 06:30:23 CRITICAL unit.test-s4m287fw/0.juju-log debug-ssh:1: test mode is enabled
unit-test-s4m287fw-0: 06:30:24 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:30:26 CRITICAL unit.test-s4m287fw/0.juju-log test mode is enabled
unit-test-s4m287fw-0: 06:30:42 CRITICAL unit.test-s4m287fw/0.juju-log debug-ssh:1: test mode is enabled
unit-test-s4m287fw-0: 06:30:43 CRITICAL unit.test-s4m287fw/0.juju-log debug-ssh:1: test mode is enabled
unit-test-s4m287fw-0: 06:31:09 ERROR unit.test-s4m287fw/0.juju-log debug-ssh:1: pre-job-metrics.json not found for runner test-s4m287fw-0-1eb7ec5ab9a8
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-s4m287fw-0-1eb7ec5ab9a8/pre-job-metrics.json'
unit-test-s4m287fw-0: 06:31:09 ERROR unit.test-s4m287fw/0.juju-log debug-ssh:1: Pre-job metrics for runner test-s4m287fw-0-1eb7ec5ab9a8 not found, stop extracting post-jobs metrics.
unit-test-s4m287fw-0: 06:34:50 CRITICAL unit.test-s4m287fw/0.juju-log image:0: test mode is enabled
unit-test-s4m287fw-0: 06:35:12 ERROR unit.test-s4m287fw/0.juju-log image:0: pre-job-metrics.json not found for runner test-s4m287fw-0-b89e3a691055
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-s4m287fw-0-b89e3a691055/pre-job-metrics.json'
unit-test-s4m287fw-0: 06:35:12 ERROR unit.test-s4m287fw/0.juju-log image:0: Pre-job metrics for runner test-s4m287fw-0-b89e3a691055 not found, stop extracting post-jobs metrics.
unit-test-s4m287fw-0: 06:35:16 ERROR unit.test-s4m287fw/0.juju-log image:0: Unable to get SSH connection for instance test-s4m287fw-0-b89e3a691055, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-s4m287fw-0-b89e3a691055, key path: /home/runner-manager/.ssh/test-s4m287fw-0-b89e3a691055.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-s4m287fw-0-b89e3a691055
unit-test-s4m287fw-0: 06:35:16 ERROR unit.test-s4m287fw/0.juju-log image:0: Failed to get SSH connection while removing test-s4m287fw-0-b89e3a691055
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 441, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-s4m287fw-0-b89e3a691055, key path: /home/runner-manager/.ssh/test-s4m287fw-0-b89e3a691055.key
unit-test-s4m287fw-0: 06:35:23 ERROR unit.test-s4m287fw/0.juju-log image:0: Unable to get SSH connection for instance test-s4m287fw-0-b89e3a691055, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-s4m287fw-0-b89e3a691055, key path: /home/runner-manager/.ssh/test-s4m287fw-0-b89e3a691055.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-s4m287fw-0-b89e3a691055
unit-test-s4m287fw-0: 06:35:26 ERROR unit.test-s4m287fw/0.juju-log image:0: Unable to get SSH connection for instance test-s4m287fw-0-b89e3a691055, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-s4m287fw-0-b89e3a691055, key path: /home/runner-manager/.ssh/test-s4m287fw-0-b89e3a691055.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-s4m287fw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-s4m287fw-0-b89e3a691055

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...